name: Simple Deploy

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with secrets
        run: |
          # Inject environment variables
          sed -i "s|{{SUPABASE_URL}}|${{ secrets.SUPABASE_URL }}|g" index.html
          sed -i "s|{{SUPABASE_ANON_KEY}}|${{ secrets.SUPABASE_ANON_KEY }}|g" index.html  
          sed -i "s|{{WHATSAPP_NUMBER}}|${{ secrets.WHATSAPP_NUMBER }}|g" index.html
          
          echo "✅ Variables injected successfully"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true